# Generated by Django 2.2 on 2019-04-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ouwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
            preserve_default=False,
        ),
    ]
