# Generated by Django 2.2 on 2019-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle_ouwner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value_month', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
