# Generated by Django 2.2 on 2019-04-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_moverotary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('value_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vehicle')),
            ],
        ),
    ]
