# Generated by Django 2.2 on 2019-04-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movemonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('moveMonthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoveMonthly')),
            ],
        ),
    ]
